#version 430 core

layout(local_size_x=1, local_size_y=1, local_size_z=1) in;

layout(rgba16_snorm)
uniform image3D a;

layout(rgba16_snorm) 
uniform image3D b;

layout(rgba16_snorm) 
uniform image3D c;

void main()
{
    ivec3 coord = ivec3(gl_GlobalInvocationID);

    vec4 av = imageLoad(a, coord);
    vec4 bv = imageLoad(b, coord);
    vec4 cv = av - bv;

    imageStore(c, coord, cv);
}